apiVersion: v1
kind: Service
metadata:
  name: new-service-service
  labels:
    app: new-service
    environment: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: new-service
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-service-deployment
  labels:
    app: new-service
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-service
      environment: dev
  template:
    metadata:
      labels:
        app: new-service
        environment: dev
    spec:
      containers:
        - name: new-service-container
          image: new-service:latest
          ports:
            - containerPort: 8080
