apiVersion: v1
kind: Service
metadata:
  name: app-store-service
  labels:
    app: app-store
    environment: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-store
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-store-deployment
  labels:
    app: app-store
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-store
      environment: dev
  template:
    metadata:
      labels:
        app: app-store
        environment: dev
    spec:
      containers:
        - name: app-store-container
          image: app-store:latest
          ports:
            - containerPort: 8080
